import { Component } from "@angular/core";
import { ConfigService } from "./config.service";
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
})
export class AppComponent {
  title = "Recruiter";
  // data:any;
  // constructor(private postData:ConfigService){}

  // ngOnInit(){

  // this.selectedItems = [
  //   { item_id: 3, item_text: 'Pune' },
  //   { item_id: 4, item_text: 'Navsari' }
  // ];

  //   this.postData.getPost().subscribe((result)=>{
  //     console.log("result",result);
  //     this.data=result;
  //   })
  // }

  itemList = [] as any;
  itemListPharma = [] as any;
  itemListfilmModeling  = [] as any;
  selectedItems = [] as any;
  selectedItemsPharma = [] as any;
  selectedItemsfilmModeling = [] as any;
  settings = {};
  settingsfilmModeling= {};

  constructor() {}
  ngOnInit() {
    this.itemList = [
      { id: 1, itemName: "portfolio", category: "Management" },
      { id: 2, itemName: "funtional", category: "Management" },
      { id: 3, itemName: "technical", category: "Management" },
      { id: 4, itemName: "Accounting", category: "Finance" },
      { id: 5, itemName: "Research skills", category: "Finance" },
      { id: 6, itemName: "Control assessment", category: "Finance" },
      { id: 7, itemName: "Stakeholder engagement", category: "Finance" },
      { id: 8, itemName: "Analytics", category: "Finance" },
      { id: 9, itemName: "Auditing", category: "Finance" },
      { id: 10, itemName: "Controller", category: "Finance" },
      { id: 11, itemName: "Bookkeeping", category: "Finance" },
      { id: 12, itemName: "Financial management", category: "Finance" },
      { id: 13, itemName: "Management experience", category: "Finance" },
      { id: 14, itemName: "Problem-solving", category: "Finance" },
      { id: 15, itemName: "Calculations", category: "Finance" },
      { id: 16, itemName: "Cash flow management", category: "Finance" },
      { id: 17, itemName: "Budgeting skills", category: "Finance" },
      { id: 18, itemName: "Tax planning", category: "Finance" },
      { id: 19, itemName: "Financial modeling", category: "Finance" },
      { id: 20, itemName: "Fraud auditing", category: "Finance" },
      { id: 21, itemName: "C", category: "Programming" },
      { id: 22, itemName: "C++", category: "Programming" },
      { id: 23, itemName: "C#", category: "Programming" },
      { id: 24, itemName: "JAVA", category: "Programming" },
      { id: 25, itemName: "PHP", category: "Programming" },
      { id: 26, itemName: "JavaScript", category: "Programming" },
      { id: 27, itemName: "Angular", category: "Programming" },
      { id: 28, itemName: "Python", category: "Programming" },
      { id: 29, itemName: "Scala", category: "Programming" },
      { id: 30, itemName: "Perl", category: "Programming" },
      { id: 31, itemName: "HTML", category: "Programming" },
      { id: 32, itemName: "CSS", category: "Programming" },
      { id: 33, itemName: "React", category: "Programming" },
      { id: 34, itemName: "Wordpress", category: "Programming" },
      { id: 35, itemName: "Ruby", category: "Programming" },
      { id: 36, itemName: "Swift", category: "Programming" },
      { id: 37, itemName: "Haskell", category: "Programming" },
      { id: 38, itemName: "Lue", category: "Programming" },
      { id: 39, itemName: "Fortran", category: "Programming" },
      { id: 40, itemName: "Pascal", category: "Programming" },
      { id: 41, itemName: "Algol", category: "Programming" },
      { id: 42, itemName: "Smalltak", category: "Programming" },
      { id: 43, itemName: "Prolog", category: "Programming" },
      { id: 44, itemName: "Query Analyzers", category: "Programming" },
      { id: 45, itemName: "Metadata management and repository usage", category: "Database" },
      { id: 46, itemName: "SQL Databases", category: "Database" },
      { id: 47, itemName: "Data analysis", category: "Database" },
      { id: 48, itemName: "Pl/Sql", category: "Database" },
      { id: 49, itemName: " Data integrity", category: "Database" },
      { id: 50, itemName: "NoSQL Databases", category: "Database" },
      { id: 51, itemName: "Relational Databases", category: "Database" },
      { id: 52, itemName: "Metadata Management", category: "Database" },
      { id: 53, itemName: "In-memory Databases", category: "Database" },
      { id: 54, itemName: " Realtime Databases", category: "Database" },
      { id: 55, itemName: " Stored Procedures", category: "Database" },
      { id: 56, itemName: "Problem Management", category: "Database" },
      { id: 57, itemName: " Transactions", category: "Database" },
      { id: 58, itemName: " Normalization", category: "Database" },
      { id: 59, itemName: " Backup and recovery", category: "Database" },
      { id: 60, itemName: "Database schema creation and management", category: "Database" },
      { id: 61, itemName: "Data modeling and database design", category: "Database" },
      { id: 62, itemName: "Visual identity Marketing & advertising", category: "Graphic Design" },
      { id: 63, itemName: "User interface", category: "Graphic Design" },
      { id: 64, itemName: "Publication Packaging", category: "Graphic Design" },
      { id: 65, itemName: "Motion Environmental", category: "Graphic Design" },
      { id: 66, itemName: "Art and illustration", category: "Graphic Design" },
      { id: 67, itemName: "Programming", category: "Testing" },
      { id: 68, itemName: "Web and App Development ", category: "degital marketing" },
      { id: 69, itemName: "Digital Business Analysis", category: "degital marketing" },
      { id: 70, itemName: "Digital Design and Data Visualization", category: "degital marketing" },
      { id: 71, itemName: "Digital Project Management", category: "degital marketing" },
      { id: 72, itemName: "Digital Product Management", category: "degital marketing" },
      { id: 73, itemName: "Data Science and Data Analytics", category: "degital marketing" },
      { id: 74, itemName: "Social Media Advertising", category: "degital marketing" },
      { id: 75, itemName: "Email Marketing", category: "degital marketing" },
      { id: 76, itemName: "Content Marketing", category: "degital marketing" },
      { id: 77, itemName: "SEO and SEM", category: "degital marketing" },
      { id: 78, itemName: "Software Engineer", category: "Testing" },
      { id: 79, itemName: "Project Manager", category: "Testing" },
      { id: 80, itemName: "Consultant", category: "Testing" },
      { id: 81, itemName: "Senior Software Engineer", category: "Testing" },
      { id: 82, itemName: "Software Developer", category: "Testing" },
      { id: 83, itemName: "Web & Android Developer", category: "Testing" },
      { id: 84, itemName: "Senior Manager", category: "Testing" },
      { id: 85, itemName: "Business Analyst", category: "Testing" },
      { id: 86, itemName: "Product Manager", category: "Testing" },
      { id: 87, itemName: "Analytics and Troubleshooting", category: "network engineer" },
      { id: 88, itemName: " Firewalls and Security", category: "network engineer" },
      { id: 89, itemName: " Networking", category: "network engineer" },
      { id: 90, itemName: "Programming Languages", category: "network engineer" },
      { id: 91, itemName: "Hardware and Infrastructure", category: "network engineer" },
      { id: 92, itemName: "DNS", category: "network engineer" },
      { id: 93, itemName: "Virtualization and Automation", category: "network engineer" },
      { id: 94, itemName: "MPLS", category: "network engineer" },
      { id: 95, itemName: "Analytical", category: "Consulting"},
      { id: 96, itemName: "Business Analyst", category: "Consulting"},
      { id: 97, itemName: "Communication", category: "Consulting"},
      { id: 98, itemName: "Time-Management", category: "Consulting"},
      { id: 99, itemName: "Problem solving", category: "Consulting"},
      { id: 100, itemName: "Delivery of results", category: "Consulting"},
      { id: 101, itemName: "Leadership", category: "Consulting"},
      { id: 102, itemName: "Teamwork", category: "Consulting"},
      { id: 103, itemName: "Functional expertise", category: "Consulting"},
      { id: 104, itemName: "Entrepreneurial spirit", category: "Consulting"},
      { id: 105, itemName: "Communication", category: "HR/Legal"},
      { id: 106, itemName: "Knowledge of Substantive Law and Legal Procedure", category: "HR/Legal"},
      { id: 107, itemName: "Time Management", category: "HR/Legal"},
      { id: 108, itemName: "Organization", category: "HR/Legal"},
      { id: 109, itemName: "Teamwork", category: "HR/Legal"},
      { id: 110, itemName: "DNS", category: "HR/Legal"},
      { id: 111, itemName: "Cisco", category: "Enterprise Applications"},
      { id: 112, itemName: "IBM", category: "Enterprise Applications"},
      { id: 113, itemName: "Informatica", category: "Enterprise Applications"},
      { id: 114, itemName: "Microsoft", category: "Enterprise Applications"},
      { id: 115, itemName: "Oracle", category: "Enterprise Applications"},
      { id: 116, itemName: "Salesforce", category: "Enterprise Applications"},
      { id: 117, itemName: "SAP", category: "Enterprise Applications"},
      { id: 118, itemName: "Database Skills", category: "Cloud Technology" },
      { id: 119, itemName: "Programming Skills", category: "Cloud Technology" },
      { id: 120, itemName: "Networking Skills", category: "Cloud Technology" },
      { id: 121, itemName: "Cloud Service Providers", category: "Cloud Technology" },
      { id: 122, itemName: "Web Services & APIs", category: "Cloud Technology" },
      { id: 123, itemName: "Information Security", category: "Cloud Technology" },
      { id: 124, itemName: "Platform Expertise", category: "Cloud Technology" },
      { id: 125, itemName: "Maintaining Databases", category: "Cloud Technology" },
      { id: 126, itemName: "Managing a Network", category: "Cloud Technology" },
      { id: 127, itemName: "Securing the Cloud Environment", category: "Cloud Technology" },
      { id: 128, itemName: "Managing Change", category: "Cloud Technology" },
      { id: 129, itemName: "Version control", category: "DevOps"},
      { id: 130, itemName: "Monitoring and analytics", category: "DevOps"},
      { id: 131, itemName: "Testing and Cloud Quality tools", category: "DevOps"},
      { id: 132, itemName: "Network protocols", category: "DevOps"},
      { id: 133, itemName: "Infrastructure Orchestration", category: "DevOps"},
      { id: 134, itemName: "Deployment automation", category: "DevOps"},
      { id: 135, itemName: "Configuration management", category: "DevOps"},
      { id: 136, itemName: "Social Selling", category: "Sales/Marketing"},
      { id: 137, itemName: "Active Listening", category: "Sales/Marketing"},
      { id: 138, itemName: "Buyer Research", category: "Sales/Marketing"},
      { id: 139, itemName: "Time Management and Planning", category: "Sales/Marketing"},
      { id: 140, itemName: "Collaboration", category: "Sales/Marketing"},
      { id: 141, itemName: "Communication", category: "Sales/Marketing"},
      { id: 142, itemName: "Territory Management", category: "Sales/Marketing"},
      { id: 143, itemName: " Business Acumen", category: "Sales/Marketing"},
      { id: 144, itemName: "Big Data Analytics", category: "DigitalTransformation"},
      { id: 145, itemName: "Machine Learning", category: "DigitalTransformation"},
      { id: 146, itemName: "Data and Digital Security", category: "DigitalTransformation"},
      { id: 147, itemName: "Mobility Management", category: "DigitalTransformation"},
      // { id: 148, itemName: "", category: "DigitalTransformation"},
      // { id: 149, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 150, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 151, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 152, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 153, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 154, itemName: "DNS", category: "DigitalTransformation"},
      // { id: 155, itemName: "DNS", category: "DigitalTransformation"},

    ];

    this.selectedItems = [
      { id: 1, itemName: "portfolio" },
      { id: 2, itemName: "funtional" },
      { id: 3, itemName: "technical" },
      { id: 4, itemName: "Fraud auditing" },
      { id: 5, itemName: "Accounting" },
      { id: 6, itemName: "Control assessment" },
      { id: 7, itemName: "Stakeholder engagement" },
      { id: 8, itemName: "Analytics" },
      { id: 9, itemName: "Auditing" },
      { id: 10, itemName: "Controller" },
      { id: 11, itemName: "Bookkeeping" },
      { id: 12, itemName: "Financial management" },
      { id: 13, itemName: "Management experience" },
      { id: 14, itemName: "Problem-solving" },
      { id: 15, itemName: "Calculations" },
      { id: 16, itemName: "Cash flow management" },
      { id: 17, itemName: "Budgeting skills" },
      { id: 18, itemName: "Tax planning" },
      { id: 19, itemName: "Financial modeling" },
      { id: 20, itemName: "C" },
      { id: 21, itemName: "C++" },
      { id: 22, itemName: "C#" },
      { id: 23, itemName: "JAVA" },
      { id: 24, itemName: "PHP" },
      { id: 25, itemName: "JavaScript" },
      { id: 26, itemName: "Angular" },
      { id: 27, itemName: "Python" },
      { id: 28, itemName: "scala" },
      { id: 29, itemName: "perl" },
      { id: 30, itemName: "HTML" },
      { id: 31, itemName: "CSS" },
      { id: 32, itemName: "SCSS" },
      { id: 33, itemName: "React" },
      { id: 34, itemName: "Wordpress" },
      { id: 35, itemName: "Ruby" },
      { id: 36, itemName: "Swift" },
      { id: 37, itemName: "Haskell" },
      { id: 38, itemName: "Lue" },
      { id: 39, itemName: "Fortran" },
      { id: 40, itemName: "Pascal" },
      { id: 41, itemName: "Python" },
      { id: 42, itemName: "Algol" },
      { id: 43, itemName: "Smalltak" },
      { id: 44, itemName: "Prolog" },
      { id: 45, itemName: "Lisp" },
      { id: 46, itemName: "Python" },
      { id: 47, itemName: "Query Analyzers" },
      { id: 48, itemName: "Metadata management and repository usage" },
      { id: 49, itemName: "SQL Databases" },
      { id: 50, itemName: "Data analysis" },
      { id: 51, itemName: "Pl/Sql" },
      { id: 52, itemName: "Data integrity" },
      { id: 53, itemName: "NoSQL Databases" },
      { id: 54, itemName: "Relational Databases" },
      { id: 55, itemName: "Metadata Management" },
      { id: 56, itemName: "In-memory Databases" },
      { id: 57, itemName: " Realtime Databases" },
      { id: 58, itemName: " Stored Procedures" },
      { id: 59, itemName: "Problem Management" },
      { id: 60, itemName: " Transactions" },
      { id: 61, itemName: " Normalization" },
      { id: 62, itemName: " Backup and recovery" },
      { id: 63, itemName: "Database schema creation and management" },
      { id: 64, itemName: "Data modeling and database design" },
      { id: 65, itemName: "Visual identity Marketing & advertising" },
      { id: 66, itemName: "User interface" },
      { id: 67, itemName: "Publication Packaging" },
      { id: 68, itemName: "Motion Environmental" },
      { id: 69, itemName: "Art and illustration" },
      { id: 70, itemName: "Programming" },
      { id: 71, itemName: "Web and App Development " },
      { id: 72, itemName: "Digital Business Analysis" },
      { id: 73, itemName: "Digital Design and Data Visualization" },
      { id: 74, itemName: "Digital Project Management" },
      { id: 75, itemName: "Digital Product Management" },
      { id: 76, itemName: "Data Science and Data Analytics" },
      { id: 77, itemName: "Social Media Advertising" },
      { id: 78, itemName: "Email Marketing" },
      { id: 79, itemName: "Content Marketing" },
      { id: 80, itemName: "SEO and SEM" },
      { id: 81, itemName: "Software Engineer" },
      { id: 82, itemName: "Project Manager" },
      { id: 83, itemName: "Consultant" },
      { id: 84, itemName: "Senior Software Engineer" },
      { id: 85, itemName: "Software Developer" },
      { id: 86, itemName: "Web & Android Developer" },
      { id: 87, itemName: "Senior Manager" },
      { id: 88, itemName: "Business Analyst" },
      { id: 89, itemName: "Product Manager" },
      { id: 90, itemName: "Analytics and Troubleshooting" },
      { id: 91, itemName: " Firewalls and Security" },
      { id: 92, itemName: " Networking" },
      { id: 93, itemName: "Programming Languages" },
      { id: 94, itemName: "Hardware and Infrastructure" },
      { id: 95, itemName: "DNS" },
      { id: 96, itemName: "Virtualization and Automation" },
      { id: 97, itemName: "MPLS" },
      { id: 98, itemName: "Analytical" },
      { id: 99, itemName: "Communication" },
      { id: 100, itemName: "Time-Management" },
      { id: 101, itemName: "Problem solving" },
      { id: 102, itemName: "Delivery of results" },
      { id: 103, itemName: "Leadership" },
      { id: 104, itemName: "Teamwork" },
      { id: 105, itemName: "Functional expertise" },
      { id: 106, itemName: "Entrepreneurial spirit" },
      { id: 107, itemName: "Communication" },
      { id: 108, itemName: "Knowledge of Substantive Law and Legal Procedure" },
      { id: 109, itemName: "Time Management" },
      { id: 110, itemName: "Organization" },
      { id: 111, itemName: "Teamwork" },
      { id: 112, itemName: "Cisco" },
      { id: 113, itemName: "IBM" },
      { id: 114, itemName: "Informatica" },
      { id: 115, itemName: "Microsoft" },
      { id: 116, itemName: "Oracle" },
      { id: 117, itemName: "Salesforce" },
      { id: 118, itemName: "SAP" },
      { id: 119, itemName: "Database Skills" },
      { id: 120, itemName: "Programming Skills" },
      { id: 121, itemName: "Networking Skills" },
      { id: 122, itemName: "Cloud Service Providers" },
      { id: 123, itemName: "Web Services & APIs" },
      { id: 124, itemName: "Information Security" },
      { id: 125, itemName: "Platform Expertise" },
      { id: 126, itemName: "Maintaining Databases" },
      { id: 127, itemName: "Securing the Cloud Environment" },
      { id: 128, itemName: "Managing a Network" },
      { id: 129, itemName: "Managing Change" },
      { id: 130, itemName: "Version control" },
      { id: 131, itemName: "Monitoring and analytics" },
      { id: 132, itemName: "Testing and Cloud Quality tools" },
      { id: 133, itemName: "Network protocols" },
      { id: 134, itemName: "Infrastructure Orchestration" },
      { id: 135, itemName: "Deployment automation" },
      { id: 136, itemName: "Configuration management" },
      { id: 137, itemName: "Social Selling" },
      { id: 138, itemName: "Active Listening" },
      { id: 139, itemName: "Buyer Research" },
      { id: 140, itemName: "Time Management and Planning" },
      { id: 141, itemName: "Collaboration" },
      { id: 142, itemName: "Communication" },
      { id: 143, itemName: "Territory Management" },
      { id: 144, itemName: " Business Acumen" },
      { id: 145, itemName: "Big Data Analytics" },
      { id: 146, itemName: "Machine Learning" },
      { id: 147, itemName: "Data and Digital Security" },
      { id: 148, itemName: "Mobility Management" },
      // { id: 149, itemName: "" },
      // { id: 150, itemName: "SAP" },
      // { id: 151, itemName: "SAP" },
      // { id: 152, itemName: "SAP" },
      // { id: 153, itemName: "SAP" },
      // { id: 154, itemName: "SAP" },
      // { id: 155, itemName: "SAP" },
    ];
// film modeling
      this.itemListfilmModeling  = [
        { id: 1, itemName: "Television", category: "Modelling"},
        { id: 2, itemName: "Ramp Modeling", category: "Modelling"},
        { id: 3, itemName: "Catalog modeling", category: "Modelling"},
        { id: 4, itemName: "Fit modeling", category: "Modelling"},
        { id: 5, itemName: "Videos modeling", category: "Modelling"},
        { id: 6, itemName: " Promotional modeling", category: "Modelling"},
        { id: 7, itemName: "Editorial modeling", category: "Modelling"},
        { id: 8, itemName: "Print advertisements modeling", category: "Modelling"},
        { id: 9, itemName: "Ozone Models Management", category: "Modelling"},
        { id: 10, itemName: "Platinum Models", category: "Modelling"},
        { id: 11, itemName: "High fashion modeling", category: "Modelling"},
        { id: 12, itemName: "good communication", category: "Costume Designer"},
        { id: 13, itemName: "Passion for design", category: "Costume Designer"},
        { id: 14, itemName: "Artistic ability", category: "Costume Designer"},
        { id: 15, itemName: "Software capabilities", category: "Costume Designer"},
        { id: 16, itemName: "Rudimentary construction knowledge", category: "Costume Designer"},
        { id: 17, itemName: "freelance", category: "Costume Designer"},
        { id: 18, itemName: "residential", category: "Costume Designer"},
        { id: 19, itemName: "academic", category: "Costume Designer"},
        { id: 20, itemName: "Dance choriography", category: "Choriographer"},
        { id: 21, itemName: "Cheerleading", category: "Choriographer"},
        { id: 22, itemName: "Marching band ", category: "Choriographer"},
        { id: 23, itemName: "Ice skating ", category: "Choriographer"},
        { id: 24, itemName: "Theater", category: "Choriographer"},
        { id: 25, itemName: "Synchronized swimming", category: "Choriographer"},
        { id: 26, itemName: "Opera", category: "Choriographer"},
        { id: 27, itemName: "Cinematography ", category: "Choriographer"},
        { id: 28, itemName: "DNS", category: "Direction"},
        { id: 29, itemName: "DNS", category: "Direction"},
        { id: 30, itemName: "DNS", category: "Direction"},
        { id: 31, itemName: "DNS", category: "Direction"},
        { id: 32, itemName: "DNS", category: "Direction"},
        { id: 33, itemName: "DNS", category: "Direction"},
        { id: 34, itemName: "DNS", category: "Direction"},
        { id: 35, itemName: "DNS", category: "Direction"},
        { id: 36, itemName: "Classical Acting", category: "Acting"},
        { id: 37, itemName: "The Chekhov Acting Technique", category: "Acting"},
        { id: 38, itemName: "Method Acting", category: "Acting"},
        { id: 39, itemName: "Meisner Acting Technique", category: "Acting"},
        { id: 40, itemName: "Practical Aesthetics Acting Technique", category: "Acting"},
        { id: 41, itemName: "Spolin Method", category: "Acting"},
        { id: 42, itemName: "Director of Photography", category: "Cameramen" },
        { id: 43, itemName: "Camera Operator", category: "Cameramen" },
        { id: 44, itemName: "First Assistant Camera", category: "Cameramen" },
        { id: 45, itemName: "Second Assistant Camera ", category: "Cameramen" },
        { id: 46, itemName: "Digital Imaging Technician ", category: "Cameramen" },
        { id: 47, itemName: "Steadicam Operator", category: "Cameramen" },
        { id: 48, itemName: "Camera Production Assistant ", category: "Cameramen" },
        { id: 49, itemName: " Data integrity", category: "Database" },
        { id: 50, itemName: "NoSQL Databases", category: "Database" },
        { id: 51, itemName: "Relational Databases", category: "Database" },
        { id: 52, itemName: "Metadata Management", category: "Database" },
        { id: 53, itemName: "In-memory Databases", category: "Database" },
        { id: 54, itemName: " Realtime Databases", category: "Database" },
        { id: 55, itemName: " Stored Procedures", category: "Database" },
        { id: 56, itemName: "Problem Management", category: "Database" },
        { id: 57, itemName: " Transactions", category: "Database" },
        { id: 58, itemName: " Normalization", category: "Database" },
        { id: 59, itemName: " Backup and recovery", category: "Database" },
        { id: 60, itemName: "Database schema creation and management", category: "Database" },
        { id: 61, itemName: "Data modeling and database design", category: "Database" },
        { id: 62, itemName: "Visual identity Marketing & advertising", category: "Graphic Design" },
        { id: 63, itemName: "User interface", category: "Graphic Design" },
        { id: 64, itemName: "Publication Packaging", category: "Graphic Design" },
        { id: 65, itemName: "Motion Environmental", category: "Graphic Design" },
        { id: 66, itemName: "Art and illustration", category: "Graphic Design" },
        { id: 67, itemName: "Programming", category: "Testing" },
        { id: 68, itemName: "Web and App Development ", category: "degital marketing" },
        { id: 69, itemName: "Digital Business Analysis", category: "degital marketing" },
        { id: 70, itemName: "Digital Design and Data Visualization", category: "degital marketing" },


];
this.itemListfilmModeling=[
  { id: 1, itemName: "Television" },
  { id: 2, itemName: "Rmp Modeling" },
  { id: 3, itemName: "Catalog modeling" },
  { id: 4, itemName: "Fit modeling" },
  { id: 5, itemName: " Videos modeling" },
  { id: 6, itemName: "Promotional modeling" },
  { id: 7, itemName: "Editorial modeling" },
  { id: 8, itemName: "Print advertisements modeling" },
  { id: 9, itemName: "Ozone Models Management" },
  { id: 10, itemName: "Platinum Models" },
  { id: 11, itemName: "High fashion modeling" },
  { id: 12, itemName: "good communication" },
  { id: 13, itemName: "Passion for design" },
  { id: 14, itemName: "Artistic ability" },
  { id: 15, itemName: "Software capabilities" },
  { id: 16, itemName: "Rudimentary construction knowledge" },
  { id: 17, itemName: "Budgeting skills" },
  { id: 18, itemName: "residential" },
  { id: 19, itemName: "academic" },
  { id: 20, itemName: "freelance" },
  { id: 21, itemName: "Dance choriography" },
  { id: 22, itemName: "Cheerleading" },
  { id: 23, itemName: "Marching band " },
  { id: 24, itemName: "Ice skating " },
  { id: 25, itemName: "Theater" },
  { id: 26, itemName: "Synchronized swimming" },
  { id: 27, itemName: "Opera" },
  { id: 28, itemName: "Cinematography " },
  { id: 29, itemName: "Direction" },
  { id: 30, itemName: "Direction" },
  { id: 31, itemName: "Direction" },
  { id: 32, itemName: "Direction" },
  { id: 33, itemName: "Direction" },
  { id: 34, itemName: "Direction" },
  { id: 35, itemName: "Direction" },
  { id: 36, itemName: "Classical Acting" },
  { id: 37, itemName: "The Chekhov Acting Technique" },
  { id: 38, itemName: "Method Acting" },
  { id: 39, itemName: "Meisner Acting Technique" },
  { id: 40, itemName: "Practical Aesthetics Acting TechniquePascal" },
  { id: 41, itemName: "Spolin Method" },
  { id: 42, itemName: "Director of Photography" },
  { id: 43, itemName: "Camera Operator" },
  { id: 44, itemName: "First Assistant Camera" },
  { id: 45, itemName: "Second Assistant Camera " },
  { id: 46, itemName: "Loader " },
  { id: 47, itemName: "Digital Imaging Technician" },
  { id: 48, itemName: "Steadicam Operator" },
  { id: 49, itemName: "Camera Production Assistant " },
  { id: 50, itemName: "Practical" },
  { id: 51, itemName: "Practical" },
  { id: 52, itemName: "Practical" },
  { id: 53, itemName: "Practical" },
  { id: 54, itemName: "Practical" },
  { id: 55, itemName: "Practical" },
  { id: 56, itemName: "Practical" },
  { id: 57, itemName: "Practical" },
  { id: 58, itemName: "Practical" },
  { id: 59, itemName: "Practical" },
  { id: 60, itemName: "Practical" },
  { id: 61, itemName: "Practical" },
  { id: 62, itemName: "Practical" },
]




this.settingsfilmModeling = {
  singleSelection: false,
  text: "Select Fields",
  selectAllText: "Select All",
  unSelectAllText: "UnSelect All",
  searchPlaceholderText: "Search Fields",
  enableSearchFilter: true,
  badgeShowLimit: 4,
  groupBy: "category",
};

    
    this.settings = {
      singleSelection: false,
      text: "Select Fields",
      selectAllText: "Select All",
      unSelectAllText: "UnSelect All",
      searchPlaceholderText: "Search Fields",
      enableSearchFilter: true,
      badgeShowLimit: 4,
      groupBy: "category",
    };
  }
  loadDataSet1() {
    this.selectedItems = [];
    this.itemList = [
      { id: 1, itemName: "Apple", category: "fruits" },
      { id: 2, itemName: "Banana", category: "fruits" },
      { id: 5, itemName: "Tomatoe", category: "vegetables" },
      { id: 6, itemName: "Potatoe", category: "vegetables" },
    ];
  }
  loadDataSet2() {
    this.selectedItems = [];
    this.itemList = [
      { id: 1, itemName: "India", category: "asia" },
      { id: 2, itemName: "Singapore", category: "asia pacific" },
      { id: 3, itemName: "Germany", category: "Europe" },
      { id: 4, itemName: "France", category: "Europe" },
      { id: 5, itemName: "South Korea", category: "asia" },
      { id: 6, itemName: "Sweden", category: "Europe" },
    ];
  }
  onItemSelect(item: any) {
    console.log(item);
    console.log(this.selectedItems);
  }
  OnItemDeSelect(item: any) {
    console.log(item);
    console.log(this.selectedItems);
  }
  onSelectAll(items: any) {
    console.log(items);
  }
  onDeSelectAll(items: any) {
    console.log(items);
  }
}
